---
- hosts: web_nodes
  become: yes
  vars:
    wp_directory: /var/www/blogasek
    database_name: blogasek
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metrics_storage_ip: 18.196.141.234
    serverdb_ip: 18.185.112.74
  tasks:
    - name: "Install apache server"
      yum:
        name: httpd
        state: latest
    - name: "Restart server httpd sever"
      service:
        name: httpd
        state: restarted
    - name: "Download wordpress"
      get_url:
        url: https://wordpress.org/latest.zip
        dest: /tmp/wordpress.zip
    - name: "Extract wordpress"
      unarchive: 
        src: /tmp/wordpress.zip
        dest: /var/www
        remote_src: yes
    - name: "Configure apache vhost"
      template:
        src: templates/vhost.conf
        dest: /etc/httpd/conf.d/blog.conf
    - name: "Add mod_status to apache config"
      template:
        src: templates/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
    - name: "Restart server httpd sever"
      service:
        name: httpd
        state: restarted 
    - name: "Create target directory"
      file: 
        path: "{{wp_directory}}"
        state: directory
    - name: "Copy wp-config"
      copy:
        src: templates/wp-config.php
        dest: "{{wp_directory}}/wp-config.php"
    - include_tasks: tasks/telegraf.yml
    
- hosts: db_nodes
  become: yes
  vars:
    wp_directory: /var/www/blogasek
    database_name: blogasek
    username: user_blogasek
    password: eloeloelo321560
    telegraf_url: https://dl.influxdata.com/telegraf/releases/telegraf-1.8.3-1.x86_64.rpm
    metrics_storage_ip: 18.196.141.234
  tasks:    
    - include_tasks: tasks/telegraf.yml
    - name: "Install mysql server"
      yum:
        name: "{{packages}}"
        state: present
      vars:
        packages: 
          - mariadb
          - mariadb-server
    - name: "Install additional mysql python dependencies"
      yum:
        name: MySQL-python
        state: present
    - name: "Start service mariadb, if not started"
      service:
        name: mariadb
        state: started
    - name: "Create a new database"
      mysql_db:
        name: "{{database_name}}"
        state: present
    - name: "Create database user"
      mysql_user:
        name: "{{username}}"
        password: "{{password}}"
        priv: '*.*:ALL'
        state: present
        host: "%"
        
- hosts: stats_nodes
  become: yes
  vars:
    influxdb_url: https://dl.influxdata.com/influxdb/releases/influxdb-1.7.1.x86_64.rpm
    grafana_url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana-5.3.4-1.x86_64.rpm
    metrics_storage_ip: 18.196.141.234
  tasks:
    - name: "Install InfluxDB"
      yum:
        name: "{{influxdb_url}}"
        state: present
    - service:
        name: influxdb
        state: restarted
    - name: "Install grafana"
      yum:
        name: "{{grafana_url}}"
        state: present
    - service:
        name: grafana-server
        state: restarted
    - name: "Create influxdb database"
      influxdb_database:
        hostname: "{{metrics_storage_ip}}"
        username: "blogasek"
        password: "blogasek"
        database_name: "statystyki"
        ssl: yes
        validate_certs: yes